### ISSUE TITLE
Adding new supporting libraries

### ISSUE THREAD

**Issue by obonhamcarter** [Allegheny-Mozilla-Fellows/textMining#22]
As new libraries are added and imported to the project (using pip), please add them to the README.md file under the Supporting Libraries Subsection. This list will help users to set up their Streamlit client of the software.

On that thought: I am wondering whether a simple bash script, or make file, could be included to install all these libraries in one command for the user's initial setup and run of the software.

**Comment by enpuyou** [comment]
@obonhamcarter Sorry I just got to see this issue here. Supposedly, user should just be able to run `pipenv install` inside of the repository to set up the virtual environment and get all the dependencies in the `Pipfile` to be installed
